version: '3.8'

networks:
    app-network:

volumes:
    app-data:

services:
    webserver:
        image: nginx:1.21.6-alpine
        container_name: webserver
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - .docker/nginx:/etc/nginx/conf.d
        networks:
            app-network:

    backend:
        build:
            context: .docker/php
            dockerfile: dockerfile
        container_name: backend
        volumes:
            - ./:/var/www
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            app-network:
    database:
        container_name: database
        image: mysql:latest
        platform: linux/x86_64
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: dinerus
            MYSQL_USER: dinerus
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./db-data:/var/lib/mysql
        networks:
            app-network:
